[package]
name = "flat-enum-tests"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
publish = false

[dev-dependencies]
flat-enum = { version = "*", path = "../flat-enum" }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
