[package]
name = "wasm-error-tests"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
publish = false

[dev-dependencies]
wasm-error = { version = "*", path = "../wasm-error", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
